name: Publish to marketplace

on: workflow_dispatch

jobs:
   build:
      name: Build and publish plugin
      runs-on: ubuntu-18.04
      steps:
         -  uses: actions/checkout@v2
         -  uses: gradle/wrapper-validation-action@v1
         -  uses: actions/cache@v1
            with:
               path: ~/.gradle/caches
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
               restore-keys: |
                  ${{ runner.os }}-gradle-
         -  uses: actions/setup-java@v1
            with:
               java-version: '15.x'
         -  name: Verify plugin
            run: ./gradlew verifyPlugin
         -  name: Build plugin
            run: ./gradlew buildPlugin
         -  name: Publish plugin
            run: ./gradlew publishPlugin
